namespace procrastinate.Resources.Strings;

public static class AppStrings
{
    private static string _currentLanguage = Preferences.Get("AppLanguage", "en");

    public static string CurrentLanguage
    {
        get => _currentLanguage;
        set
        {
            _currentLanguage = value;
            Preferences.Set("AppLanguage", value);
        }
    }

    public static readonly Dictionary<string, string> SupportedLanguages = new()
    {
        { "en", "English" },
        { "fr", "Français" },
        { "es", "Español" },
        { "pt", "Português" },
        { "nl", "Nederlands" },
        { "cs", "Čeština" }
    };

    private static readonly Dictionary<string, Dictionary<string, string>> Translations = new()
    {
        ["en"] = new()
        {
            // General
            ["AppName"] = "Procrastinate",
            ["Settings"] = "Settings",
            ["Accessibility"] = "Accessibility",
            ["HighContrastMode"] = "High Contrast Mode",
            ["HighContrastDesc"] = "Use higher contrast colors for better visibility",
            ["ThemePreview"] = "Theme Preview",
            ["CurrentTheme"] = "Current: {0} Theme",
            ["DefaultTheme"] = "Default",
            ["HighContrast"] = "High Contrast",
            ["ChangesApply"] = "Changes apply immediately",
            ["Language"] = "Language",
            
            // Tasks
            ["TodaysTasks"] = "Today's Tasks",
            ["YourProductivityList"] = "Your productivity list:",
            ["TakeABreak"] = "Take a break",
            ["DoingGreat"] = "You're doing great! Only 1 task today!",
            ["AddMoreTasks"] = "Add More Tasks",
            ["Congratulations"] = "Congratulations! You completed ALL your tasks!",
            ["NeedAnotherBreak"] = "Wait... you still need another break!",
            
            // Games
            ["MiniGames"] = "Mini-Games",
            ["ProductivityOverrated"] = "Because productivity is overrated!",
            ["ShuffleGames"] = "Shuffle Games",
            ["Score"] = "Score: {0}",
            ["GameOver"] = "Game Over! Final Score: {0}",
            ["StartGame"] = "Start Game",
            ["NewGame"] = "New Game",
            ["YourTurn"] = "Your turn (X)",
            ["AIThinking"] = "AI thinking...",
            ["YouWin"] = "You win!",
            ["AIWins"] = "AI wins!",
            ["Draw"] = "It's a draw!",
            ["Clicks"] = "Clicks: {0}",
            ["StartChallenge"] = "Start Challenge",
            ["WaitForGreen"] = "Wait for green!",
            ["TapNow"] = "TAP NOW!",
            ["TooEarly"] = "Too early! Try again.",
            ["ReactionTime"] = "Reaction time: {0}ms",
            ["TapStartToBegin"] = "Tap 'Start' to begin",
            
            // Excuses
            ["ExcuseGenerator"] = "Excuse Generator",
            ["NeedAReason"] = "Need a reason to not do something? We got you!",
            ["TapForExcuse"] = "Tap the button for a fresh excuse!",
            ["GenerateExcuse"] = "Generate Excuse",
            ["CopyToClipboard"] = "Copy to Clipboard",
            ["Copied"] = "Copied!",
            ["ExcusesGenerated"] = "Excuses generated today: {0}",
            
            // Stats
            ["YourStats"] = "Your Stats",
            ["BeProud"] = "Be proud of your accomplishments!",
            ["TasksAvoided"] = "Tasks Avoided",
            ["BreaksTaken"] = "Breaks Taken",
            ["ExcusesGeneratedStat"] = "Excuses Generated",
            ["GamesPlayed"] = "Games Played",
            ["AchievementUnlocked"] = "Achievement Unlocked",
            ["GettingStarted"] = "Getting Started: Open the app!",
            ["BeginnerProcrastinator"] = "Beginner Procrastinator",
            ["LegendaryProcrastinator"] = "LEGENDARY PROCRASTINATOR",
            
            // Game names
            ["SimonSays"] = "Simon Says",
            ["SimonSaysDesc"] = "Watch the pattern and repeat it!",
            ["ClickSpeed"] = "Click Speed",
            ["ClickSpeedDesc"] = "How many clicks in 5 seconds?",
            ["ReactionTimeGame"] = "Reaction Time",
            ["ReactionTimeDesc"] = "Wait for green, then tap!",
            ["TicTacToe"] = "Tic Tac Toe",
            ["TicTacToeDesc"] = "Classic X and O game!",
            ["Minesweeper"] = "Minesweeper",
            ["MinesweeperDesc"] = "Find all safe cells!",
            ["TiltSnake"] = "Tilt Snake",
            ["TiltSnakeDesc"] = "Tilt your phone to guide the snake!",
            ["MemoryMatch"] = "Memory Match",
            ["MemoryMatchDesc"] = "Find matching pairs!",
            ["NumberGuess"] = "Number Guess",
            ["NumberGuessDesc"] = "Guess the number 1-100!",
            ["WhackAMole"] = "Whack-a-Mole",
            ["WhackAMoleDesc"] = "Tap the moles as fast as you can!"
        },
        
        ["fr"] = new()
        {
            ["AppName"] = "Procrastiner",
            ["Settings"] = "Paramètres",
            ["Accessibility"] = "Accessibilité",
            ["HighContrastMode"] = "Mode contraste élevé",
            ["HighContrastDesc"] = "Utiliser des couleurs plus contrastées",
            ["ThemePreview"] = "Aperçu du thème",
            ["CurrentTheme"] = "Actuel: Thème {0}",
            ["DefaultTheme"] = "Par défaut",
            ["HighContrast"] = "Contraste élevé",
            ["ChangesApply"] = "Les changements s'appliquent immédiatement",
            ["Language"] = "Langue",
            
            ["TodaysTasks"] = "Tâches du jour",
            ["YourProductivityList"] = "Votre liste de productivité:",
            ["TakeABreak"] = "Prendre une pause",
            ["DoingGreat"] = "Vous êtes super! Une seule tâche aujourd'hui!",
            ["AddMoreTasks"] = "Ajouter des tâches",
            ["Congratulations"] = "Félicitations! Vous avez terminé TOUTES vos tâches!",
            ["NeedAnotherBreak"] = "Attendez... vous avez encore besoin d'une pause!",
            
            ["MiniGames"] = "Mini-Jeux",
            ["ProductivityOverrated"] = "Parce que la productivité est surfaite!",
            ["ShuffleGames"] = "Mélanger les jeux",
            ["Score"] = "Score: {0}",
            ["GameOver"] = "Fin de partie! Score final: {0}",
            ["StartGame"] = "Commencer",
            ["NewGame"] = "Nouvelle partie",
            ["YourTurn"] = "Votre tour (X)",
            ["AIThinking"] = "L'IA réfléchit...",
            ["YouWin"] = "Vous avez gagné!",
            ["AIWins"] = "L'IA gagne!",
            ["Draw"] = "Match nul!",
            ["Clicks"] = "Clics: {0}",
            ["StartChallenge"] = "Commencer le défi",
            ["WaitForGreen"] = "Attendez le vert!",
            ["TapNow"] = "APPUYEZ!",
            ["TooEarly"] = "Trop tôt! Réessayez.",
            ["ReactionTime"] = "Temps de réaction: {0}ms",
            ["TapStartToBegin"] = "Appuyez sur 'Commencer'",
            
            ["ExcuseGenerator"] = "Générateur d'excuses",
            ["NeedAReason"] = "Besoin d'une raison pour ne rien faire? On vous aide!",
            ["TapForExcuse"] = "Appuyez pour une nouvelle excuse!",
            ["GenerateExcuse"] = "Générer une excuse",
            ["CopyToClipboard"] = "Copier",
            ["Copied"] = "Copié!",
            ["ExcusesGenerated"] = "Excuses générées aujourd'hui: {0}",
            
            ["YourStats"] = "Vos statistiques",
            ["BeProud"] = "Soyez fier de vos accomplissements!",
            ["TasksAvoided"] = "Tâches évitées",
            ["BreaksTaken"] = "Pauses prises",
            ["ExcusesGeneratedStat"] = "Excuses générées",
            ["GamesPlayed"] = "Jeux joués",
            ["AchievementUnlocked"] = "Succès débloqué",
            ["GettingStarted"] = "Début: Ouvrir l'appli!",
            ["BeginnerProcrastinator"] = "Procrastinateur débutant",
            ["LegendaryProcrastinator"] = "PROCRASTINATEUR LÉGENDAIRE",
            
            ["SimonSays"] = "Jacques a dit",
            ["SimonSaysDesc"] = "Observez et répétez le motif!",
            ["ClickSpeed"] = "Vitesse de clic",
            ["ClickSpeedDesc"] = "Combien de clics en 5 secondes?",
            ["ReactionTimeGame"] = "Temps de réaction",
            ["ReactionTimeDesc"] = "Attendez le vert, puis appuyez!",
            ["TicTacToe"] = "Morpion",
            ["TicTacToeDesc"] = "Le classique X et O!",
            ["Minesweeper"] = "Démineur",
            ["MinesweeperDesc"] = "Trouvez les cases sûres!",
            ["TiltSnake"] = "Serpent inclinable",
            ["TiltSnakeDesc"] = "Inclinez pour guider le serpent!",
            ["MemoryMatch"] = "Memory",
            ["MemoryMatchDesc"] = "Trouvez les paires!",
            ["NumberGuess"] = "Devinez le nombre",
            ["NumberGuessDesc"] = "Devinez le nombre 1-100!",
            ["WhackAMole"] = "Tape-taupe",
            ["WhackAMoleDesc"] = "Tapez les taupes rapidement!"
        },
        
        ["es"] = new()
        {
            ["AppName"] = "Procrastinar",
            ["Settings"] = "Ajustes",
            ["Accessibility"] = "Accesibilidad",
            ["HighContrastMode"] = "Modo alto contraste",
            ["HighContrastDesc"] = "Usar colores de mayor contraste",
            ["ThemePreview"] = "Vista previa del tema",
            ["CurrentTheme"] = "Actual: Tema {0}",
            ["DefaultTheme"] = "Predeterminado",
            ["HighContrast"] = "Alto contraste",
            ["ChangesApply"] = "Los cambios se aplican inmediatamente",
            ["Language"] = "Idioma",
            
            ["TodaysTasks"] = "Tareas de hoy",
            ["YourProductivityList"] = "Tu lista de productividad:",
            ["TakeABreak"] = "Tomar un descanso",
            ["DoingGreat"] = "¡Lo estás haciendo genial! ¡Solo 1 tarea hoy!",
            ["AddMoreTasks"] = "Añadir más tareas",
            ["Congratulations"] = "¡Felicidades! ¡Completaste TODAS tus tareas!",
            ["NeedAnotherBreak"] = "Espera... ¡aún necesitas otro descanso!",
            
            ["MiniGames"] = "Mini-Juegos",
            ["ProductivityOverrated"] = "¡Porque la productividad está sobrevalorada!",
            ["ShuffleGames"] = "Mezclar juegos",
            ["Score"] = "Puntuación: {0}",
            ["GameOver"] = "¡Fin del juego! Puntuación final: {0}",
            ["StartGame"] = "Empezar",
            ["NewGame"] = "Nuevo juego",
            ["YourTurn"] = "Tu turno (X)",
            ["AIThinking"] = "La IA está pensando...",
            ["YouWin"] = "¡Ganaste!",
            ["AIWins"] = "¡La IA gana!",
            ["Draw"] = "¡Empate!",
            ["Clicks"] = "Clics: {0}",
            ["StartChallenge"] = "Empezar desafío",
            ["WaitForGreen"] = "¡Espera el verde!",
            ["TapNow"] = "¡TOCA AHORA!",
            ["TooEarly"] = "¡Muy pronto! Intenta de nuevo.",
            ["ReactionTime"] = "Tiempo de reacción: {0}ms",
            ["TapStartToBegin"] = "Toca 'Empezar' para comenzar",
            
            ["ExcuseGenerator"] = "Generador de excusas",
            ["NeedAReason"] = "¿Necesitas una razón para no hacer algo? ¡Te ayudamos!",
            ["TapForExcuse"] = "¡Toca el botón para una nueva excusa!",
            ["GenerateExcuse"] = "Generar excusa",
            ["CopyToClipboard"] = "Copiar",
            ["Copied"] = "¡Copiado!",
            ["ExcusesGenerated"] = "Excusas generadas hoy: {0}",
            
            ["YourStats"] = "Tus estadísticas",
            ["BeProud"] = "¡Siéntete orgulloso de tus logros!",
            ["TasksAvoided"] = "Tareas evitadas",
            ["BreaksTaken"] = "Descansos tomados",
            ["ExcusesGeneratedStat"] = "Excusas generadas",
            ["GamesPlayed"] = "Juegos jugados",
            ["AchievementUnlocked"] = "Logro desbloqueado",
            ["GettingStarted"] = "Inicio: ¡Abrir la app!",
            ["BeginnerProcrastinator"] = "Procrastinador principiante",
            ["LegendaryProcrastinator"] = "PROCRASTINADOR LEGENDARIO",
            
            ["SimonSays"] = "Simón dice",
            ["SimonSaysDesc"] = "¡Observa el patrón y repítelo!",
            ["ClickSpeed"] = "Velocidad de clic",
            ["ClickSpeedDesc"] = "¿Cuántos clics en 5 segundos?",
            ["ReactionTimeGame"] = "Tiempo de reacción",
            ["ReactionTimeDesc"] = "¡Espera el verde y toca!",
            ["TicTacToe"] = "Tres en raya",
            ["TicTacToeDesc"] = "¡El clásico X y O!",
            ["Minesweeper"] = "Buscaminas",
            ["MinesweeperDesc"] = "¡Encuentra las celdas seguras!",
            ["TiltSnake"] = "Serpiente inclinable",
            ["TiltSnakeDesc"] = "¡Inclina el teléfono para guiar la serpiente!",
            ["MemoryMatch"] = "Memoria",
            ["MemoryMatchDesc"] = "¡Encuentra los pares!",
            ["NumberGuess"] = "Adivina el número",
            ["NumberGuessDesc"] = "¡Adivina el número 1-100!",
            ["WhackAMole"] = "Golpea al topo",
            ["WhackAMoleDesc"] = "¡Golpea los topos lo más rápido posible!"
        },
        
        ["pt"] = new()
        {
            ["AppName"] = "Procrastinar",
            ["Settings"] = "Configurações",
            ["Accessibility"] = "Acessibilidade",
            ["HighContrastMode"] = "Modo alto contraste",
            ["HighContrastDesc"] = "Usar cores de maior contraste",
            ["ThemePreview"] = "Prévia do tema",
            ["CurrentTheme"] = "Atual: Tema {0}",
            ["DefaultTheme"] = "Padrão",
            ["HighContrast"] = "Alto contraste",
            ["ChangesApply"] = "As alterações se aplicam imediatamente",
            ["Language"] = "Idioma",
            
            ["TodaysTasks"] = "Tarefas de hoje",
            ["YourProductivityList"] = "Sua lista de produtividade:",
            ["TakeABreak"] = "Fazer uma pausa",
            ["DoingGreat"] = "Você está indo muito bem! Só 1 tarefa hoje!",
            ["AddMoreTasks"] = "Adicionar mais tarefas",
            ["Congratulations"] = "Parabéns! Você completou TODAS as suas tarefas!",
            ["NeedAnotherBreak"] = "Espere... você ainda precisa de outra pausa!",
            
            ["MiniGames"] = "Mini-Jogos",
            ["ProductivityOverrated"] = "Porque produtividade é superestimada!",
            ["ShuffleGames"] = "Embaralhar jogos",
            ["Score"] = "Pontuação: {0}",
            ["GameOver"] = "Fim de jogo! Pontuação final: {0}",
            ["StartGame"] = "Começar",
            ["NewGame"] = "Novo jogo",
            ["YourTurn"] = "Sua vez (X)",
            ["AIThinking"] = "A IA está pensando...",
            ["YouWin"] = "Você ganhou!",
            ["AIWins"] = "A IA ganhou!",
            ["Draw"] = "Empate!",
            ["Clicks"] = "Cliques: {0}",
            ["StartChallenge"] = "Iniciar desafio",
            ["WaitForGreen"] = "Espere pelo verde!",
            ["TapNow"] = "TOQUE AGORA!",
            ["TooEarly"] = "Muito cedo! Tente novamente.",
            ["ReactionTime"] = "Tempo de reação: {0}ms",
            ["TapStartToBegin"] = "Toque em 'Começar' para iniciar",
            
            ["ExcuseGenerator"] = "Gerador de desculpas",
            ["NeedAReason"] = "Precisa de uma razão para não fazer algo? Nós ajudamos!",
            ["TapForExcuse"] = "Toque no botão para uma nova desculpa!",
            ["GenerateExcuse"] = "Gerar desculpa",
            ["CopyToClipboard"] = "Copiar",
            ["Copied"] = "Copiado!",
            ["ExcusesGenerated"] = "Desculpas geradas hoje: {0}",
            
            ["YourStats"] = "Suas estatísticas",
            ["BeProud"] = "Tenha orgulho das suas conquistas!",
            ["TasksAvoided"] = "Tarefas evitadas",
            ["BreaksTaken"] = "Pausas feitas",
            ["ExcusesGeneratedStat"] = "Desculpas geradas",
            ["GamesPlayed"] = "Jogos jogados",
            ["AchievementUnlocked"] = "Conquista desbloqueada",
            ["GettingStarted"] = "Início: Abrir o app!",
            ["BeginnerProcrastinator"] = "Procrastinador iniciante",
            ["LegendaryProcrastinator"] = "PROCRASTINADOR LENDÁRIO",
            
            ["SimonSays"] = "Simon diz",
            ["SimonSaysDesc"] = "Observe o padrão e repita!",
            ["ClickSpeed"] = "Velocidade de clique",
            ["ClickSpeedDesc"] = "Quantos cliques em 5 segundos?",
            ["ReactionTimeGame"] = "Tempo de reação",
            ["ReactionTimeDesc"] = "Espere pelo verde e toque!",
            ["TicTacToe"] = "Jogo da velha",
            ["TicTacToeDesc"] = "O clássico X e O!",
            ["Minesweeper"] = "Campo minado",
            ["MinesweeperDesc"] = "Encontre as células seguras!",
            ["TiltSnake"] = "Cobra inclinável",
            ["TiltSnakeDesc"] = "Incline o telefone para guiar a cobra!",
            ["MemoryMatch"] = "Jogo da memória",
            ["MemoryMatchDesc"] = "Encontre os pares!",
            ["NumberGuess"] = "Adivinhe o número",
            ["NumberGuessDesc"] = "Adivinhe o número 1-100!",
            ["WhackAMole"] = "Acerte a toupeira",
            ["WhackAMoleDesc"] = "Acerte as toupeiras o mais rápido possível!"
        },
        
        ["nl"] = new()
        {
            ["AppName"] = "Uitstellen",
            ["Settings"] = "Instellingen",
            ["Accessibility"] = "Toegankelijkheid",
            ["HighContrastMode"] = "Hoog contrast modus",
            ["HighContrastDesc"] = "Gebruik kleuren met hoger contrast",
            ["ThemePreview"] = "Thema voorbeeld",
            ["CurrentTheme"] = "Huidig: {0} Thema",
            ["DefaultTheme"] = "Standaard",
            ["HighContrast"] = "Hoog contrast",
            ["ChangesApply"] = "Wijzigingen worden direct toegepast",
            ["Language"] = "Taal",
            
            ["TodaysTasks"] = "Taken van vandaag",
            ["YourProductivityList"] = "Je productiviteitslijst:",
            ["TakeABreak"] = "Neem een pauze",
            ["DoingGreat"] = "Je doet het geweldig! Maar 1 taak vandaag!",
            ["AddMoreTasks"] = "Meer taken toevoegen",
            ["Congratulations"] = "Gefeliciteerd! Je hebt AL je taken voltooid!",
            ["NeedAnotherBreak"] = "Wacht... je hebt nog een pauze nodig!",
            
            ["MiniGames"] = "Mini-Spelletjes",
            ["ProductivityOverrated"] = "Omdat productiviteit overschat wordt!",
            ["ShuffleGames"] = "Spelletjes shuffelen",
            ["Score"] = "Score: {0}",
            ["GameOver"] = "Game Over! Eindscore: {0}",
            ["StartGame"] = "Starten",
            ["NewGame"] = "Nieuw spel",
            ["YourTurn"] = "Jouw beurt (X)",
            ["AIThinking"] = "AI denkt na...",
            ["YouWin"] = "Je hebt gewonnen!",
            ["AIWins"] = "AI wint!",
            ["Draw"] = "Gelijkspel!",
            ["Clicks"] = "Klikken: {0}",
            ["StartChallenge"] = "Start uitdaging",
            ["WaitForGreen"] = "Wacht op groen!",
            ["TapNow"] = "TIK NU!",
            ["TooEarly"] = "Te vroeg! Probeer opnieuw.",
            ["ReactionTime"] = "Reactietijd: {0}ms",
            ["TapStartToBegin"] = "Tik op 'Starten' om te beginnen",
            
            ["ExcuseGenerator"] = "Excuusgenerator",
            ["NeedAReason"] = "Een reden nodig om iets niet te doen? Wij helpen!",
            ["TapForExcuse"] = "Tik voor een nieuw excuus!",
            ["GenerateExcuse"] = "Genereer excuus",
            ["CopyToClipboard"] = "Kopiëren",
            ["Copied"] = "Gekopieerd!",
            ["ExcusesGenerated"] = "Excuses gegenereerd vandaag: {0}",
            
            ["YourStats"] = "Jouw statistieken",
            ["BeProud"] = "Wees trots op je prestaties!",
            ["TasksAvoided"] = "Taken vermeden",
            ["BreaksTaken"] = "Pauzes genomen",
            ["ExcusesGeneratedStat"] = "Excuses gegenereerd",
            ["GamesPlayed"] = "Spelletjes gespeeld",
            ["AchievementUnlocked"] = "Prestatie ontgrendeld",
            ["GettingStarted"] = "Begin: Open de app!",
            ["BeginnerProcrastinator"] = "Beginner uitstelaar",
            ["LegendaryProcrastinator"] = "LEGENDARISCHE UITSTELAAR",
            
            ["SimonSays"] = "Simon zegt",
            ["SimonSaysDesc"] = "Kijk naar het patroon en herhaal!",
            ["ClickSpeed"] = "Kliksnelheid",
            ["ClickSpeedDesc"] = "Hoeveel klikken in 5 seconden?",
            ["ReactionTimeGame"] = "Reactietijd",
            ["ReactionTimeDesc"] = "Wacht op groen en tik!",
            ["TicTacToe"] = "Boter-kaas-en-eieren",
            ["TicTacToeDesc"] = "Het klassieke X en O spel!",
            ["Minesweeper"] = "Mijnenveger",
            ["MinesweeperDesc"] = "Vind alle veilige cellen!",
            ["TiltSnake"] = "Kantel slang",
            ["TiltSnakeDesc"] = "Kantel je telefoon om de slang te leiden!",
            ["MemoryMatch"] = "Memory",
            ["MemoryMatchDesc"] = "Vind de paren!",
            ["NumberGuess"] = "Raad het getal",
            ["NumberGuessDesc"] = "Raad het getal 1-100!",
            ["WhackAMole"] = "Mep de mol",
            ["WhackAMoleDesc"] = "Mep de mollen zo snel mogelijk!"
        },
        
        ["cs"] = new()
        {
            ["AppName"] = "Prokrastinovat",
            ["Settings"] = "Nastavení",
            ["Accessibility"] = "Přístupnost",
            ["HighContrastMode"] = "Režim vysokého kontrastu",
            ["HighContrastDesc"] = "Použít barvy s vyšším kontrastem",
            ["ThemePreview"] = "Náhled motivu",
            ["CurrentTheme"] = "Aktuální: {0} motiv",
            ["DefaultTheme"] = "Výchozí",
            ["HighContrast"] = "Vysoký kontrast",
            ["ChangesApply"] = "Změny se projeví okamžitě",
            ["Language"] = "Jazyk",
            
            ["TodaysTasks"] = "Dnešní úkoly",
            ["YourProductivityList"] = "Váš seznam produktivity:",
            ["TakeABreak"] = "Dát si pauzu",
            ["DoingGreat"] = "Jde vám to skvěle! Dnes jen 1 úkol!",
            ["AddMoreTasks"] = "Přidat další úkoly",
            ["Congratulations"] = "Gratulujeme! Dokončili jste VŠECHNY své úkoly!",
            ["NeedAnotherBreak"] = "Počkejte... stále potřebujete další pauzu!",
            
            ["MiniGames"] = "Mini-hry",
            ["ProductivityOverrated"] = "Protože produktivita je přeceňovaná!",
            ["ShuffleGames"] = "Zamíchat hry",
            ["Score"] = "Skóre: {0}",
            ["GameOver"] = "Konec hry! Finální skóre: {0}",
            ["StartGame"] = "Začít",
            ["NewGame"] = "Nová hra",
            ["YourTurn"] = "Váš tah (X)",
            ["AIThinking"] = "AI přemýšlí...",
            ["YouWin"] = "Vyhráli jste!",
            ["AIWins"] = "AI vyhrála!",
            ["Draw"] = "Remíza!",
            ["Clicks"] = "Kliknutí: {0}",
            ["StartChallenge"] = "Začít výzvu",
            ["WaitForGreen"] = "Čekejte na zelenou!",
            ["TapNow"] = "KLEPNĚTE!",
            ["TooEarly"] = "Příliš brzy! Zkuste znovu.",
            ["ReactionTime"] = "Reakční čas: {0}ms",
            ["TapStartToBegin"] = "Klepněte na 'Začít'",
            
            ["ExcuseGenerator"] = "Generátor výmluv",
            ["NeedAReason"] = "Potřebujete důvod něco nedělat? Pomůžeme!",
            ["TapForExcuse"] = "Klepněte pro novou výmluvu!",
            ["GenerateExcuse"] = "Generovat výmluvu",
            ["CopyToClipboard"] = "Kopírovat",
            ["Copied"] = "Zkopírováno!",
            ["ExcusesGenerated"] = "Dnes vygenerované výmluvy: {0}",
            
            ["YourStats"] = "Vaše statistiky",
            ["BeProud"] = "Buďte hrdí na své úspěchy!",
            ["TasksAvoided"] = "Vyhnuté úkoly",
            ["BreaksTaken"] = "Pauzy",
            ["ExcusesGeneratedStat"] = "Vygenerované výmluvy",
            ["GamesPlayed"] = "Odehrané hry",
            ["AchievementUnlocked"] = "Odemčený úspěch",
            ["GettingStarted"] = "Začátek: Otevřít aplikaci!",
            ["BeginnerProcrastinator"] = "Začínající prokrastinátor",
            ["LegendaryProcrastinator"] = "LEGENDÁRNÍ PROKRASTINÁTOR",
            
            ["SimonSays"] = "Šimon říká",
            ["SimonSaysDesc"] = "Sledujte vzor a opakujte!",
            ["ClickSpeed"] = "Rychlost klikání",
            ["ClickSpeedDesc"] = "Kolik kliknutí za 5 sekund?",
            ["ReactionTimeGame"] = "Reakční čas",
            ["ReactionTimeDesc"] = "Čekejte na zelenou a klepněte!",
            ["TicTacToe"] = "Piškvorky",
            ["TicTacToeDesc"] = "Klasická hra X a O!",
            ["Minesweeper"] = "Hledání min",
            ["MinesweeperDesc"] = "Najděte všechna bezpečná pole!",
            ["TiltSnake"] = "Naklápěcí had",
            ["TiltSnakeDesc"] = "Nakloňte telefon a veďte hada!",
            ["MemoryMatch"] = "Pexeso",
            ["MemoryMatchDesc"] = "Najděte dvojice!",
            ["NumberGuess"] = "Hádej číslo",
            ["NumberGuessDesc"] = "Hádejte číslo 1-100!",
            ["WhackAMole"] = "Mlátička krtků",
            ["WhackAMoleDesc"] = "Mlať krtky co nejrychleji!"
        }
    };

    public static string Get(string key)
    {
        if (Translations.TryGetValue(_currentLanguage, out var lang) && lang.TryGetValue(key, out var value))
            return value;
        if (Translations["en"].TryGetValue(key, out var fallback))
            return fallback;
        return key;
    }

    public static string Get(string key, params object[] args)
    {
        return string.Format(Get(key), args);
    }
}
